name: Add issue to project

on:
  workflow_dispatch:
  push: 
    branches:
    - develop
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Start adding issue to the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-issue-to-project@main
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/users/itimotin/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug
